{% set name = "openapi-python-client" %}
{% set version = "0.10.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openapi-python-client-{{ version }}.tar.gz
  sha256: 3799afa5eb61b7130dd6dd545ec9b41f0061f082ecbf6d2d737debacd8da6536

build:
  number: 0
  noarch: python
  entry_points:
    - openapi-python-client = openapi_python_client.cli:app
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6
  run:
    - attrs >=21.0.0,<22.0.0
    - autoflake >=1.4,<2.0
    - black
    - colorama >=0.4.3,<0.5.0
    - httpx >=0.15.4,<0.21.0
    - importlib_metadata >=2.0.0
    - isort >=5.0.5,<6.0.0
    - jinja2 >=3.0.0,<4.0.0
    - pydantic >=1.6.1,<2.0.0
    - python >=3.6
    - python-dateutil >=2.8.1,<3.0.0
    - pyyaml >=5.3.1,<6.0.0
    - shellingham >=1.3.2,<2.0.0
    - typer >=0.3,<0.4
    - typing-extensions

test:
  imports:
    - openapi_python_client
    - openapi_python_client.parser
  commands:
    - pip check
    - openapi-python-client --help
  requires:
    - pip

about:
  home: https://github.com/triaxtec/openapi-python-client
  summary: Generate modern Python clients from OpenAPI
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
