{% set name = "openapi-python-client" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openapi_python_client-{{ version }}.tar.gz
  sha256: c1b76d97d1276462445cded66b8e0c9095fa11002f695e5dcc212b45b8bfee9c

build:
  number: 0
  noarch: python
  entry_points:
    - openapi-python-client = openapi_python_client.cli:app
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.8
  run:
    - attrs >=21.3.0
    - colorama >=0.4.3,<0.5.0
    - httpx >=0.20.0,<0.26.0
    - jinja2 >=3.0.0,<4.0.0
    - pydantic >=2.1.1,<3
    - python >=3.8
    - python-dateutil >=2.8.1,<3.0.0
    - pyyaml >=6.0,<7.0
    - ruff >=0.1.2
    - shellingham >=1.3.2,<2.0.0
    - typer >=0.6,<0.10
    - typing-extensions >=4.8.0,<5.0

test:
  imports:
    - openapi_python_client
  commands:
    - pip check
    - openapi-python-client --help
  requires:
    - pip

about:
  home: https://github.com/triaxtec/openapi-python-client
  summary: Generate modern Python clients from OpenAPI
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
    - tdsmith
