{% set name = "openapi-python-client" %}
{% set version = "0.26.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/openapi_python_client-{{ version }}.tar.gz
  sha256: e3832f0ef074a0ab591d1eeb5d3dab2ca820cd0349f7e79d9663b7b21206be5d

build:
  number: 0
  noarch: python
  entry_points:
    - openapi-python-client = openapi_python_client.cli:app
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - hatchling
    - python {{ python_min }}
  run:
    - attrs >=22.2.0
    - colorama >=0.4.3
    - httpx >=0.23.0,<0.29.0
    - jinja2 >=3.0.0,<4.0.0
    - pydantic >=2.10,<3.0.0
    - python >={{ python_min }}
    - python-dateutil >=2.8.1,<3.0.0
    - ruamel.yaml >=0.18.6,<0.19.0
    - ruff >=0.2,<0.13
    - shellingham >=1.3.2,<2.0.0
    - typer >=0.6,<0.17
    - typing-extensions >=4.8.0,<5.0

test:
  imports:
    - openapi_python_client
  commands:
    - pip check
    - openapi-python-client --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/triaxtec/openapi-python-client
  summary: Generate modern Python clients from OpenAPI
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
    - tdsmith
