{% set name = "openapi-python-client" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openapi-python-client-{{ version }}.tar.gz
  sha256: 9cf36bad56a166456bb2e2f1236c0f800df4c149723f91fd2a5e329e0a0b4ac6

build:
  number: 1
  noarch: python
  entry_points:
    - openapi-python-client = openapi_python_client.cli:app
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.7
  run:
    - attrs >=21.3.0
    - autoflake >=1.4,<2.0
    - black
    - colorama >=0.4.3,<0.5.0
    - httpx >=0.15.4,<0.23.0
    - importlib_metadata >2,<5
    - isort >=5.0.5,<6.0.0
    - jinja2 >=3.0.0,<4.0.0
    - pydantic >=1.6.1,<2.0.0
    - python >=3.7
    - python-dateutil >=2.8.1,<3.0.0
    - pyyaml >=6.0,<7.0
    - shellingham >=1.3.2,<2.0.0
    - typer >=0.4,<0.5
    - typing-extensions

test:
  imports:
    - openapi_python_client
  commands:
    - pip check
    - openapi-python-client --help
  requires:
    - pip

about:
  home: https://github.com/triaxtec/openapi-python-client
  summary: Generate modern Python clients from OpenAPI
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
