{% set name = "openapi-python-client" %}
{% set version = "0.21.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openapi_python_client-{{ version }}.tar.gz
  sha256: 019cb0191b48eb51206af98b2f65c516067df908a10b5d4fe6de333c9ebcb93d

build:
  number: 0
  noarch: python
  entry_points:
    - openapi-python-client = openapi_python_client.cli:app
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - hatchling
    - python >=3.8
  run:
    - attrs >=21.3.0
    - colorama >=0.4.3
    - httpx >=0.20.0,<0.28.0
    - jinja2 >=3.0.0,<4.0.0
    - pydantic >=2.1.1,<3
    - python >=3.8
    - python-dateutil >=2.8.1,<3.0.0
    - ruamel.yaml >=0.18.6,<0.19.0
    - ruff >=0.2,<0.5
    - shellingham >=1.3.2,<2.0.0
    - typer >=0.6,<0.13
    - typing-extensions >=4.8.0,<5.0

test:
  imports:
    - openapi_python_client
  commands:
    - pip check
    - openapi-python-client --help
  requires:
    - pip

about:
  home: https://github.com/triaxtec/openapi-python-client
  summary: Generate modern Python clients from OpenAPI
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
    - tdsmith
